//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagementSystemBE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public delivery()
        {
            this.Delivery_Images = new HashSet<Delivery_Images>();
        }
    
        public int id { get; set; }
        public Nullable<int> fixture_id { get; set; }
        public Nullable<int> team_id { get; set; }
        public Nullable<int> over_number { get; set; }
        public Nullable<int> ball_number { get; set; }
        public Nullable<int> runs_scored { get; set; }
        public Nullable<int> striker_id { get; set; }
        public Nullable<int> non_striker_id { get; set; }
        public Nullable<int> bowler_id { get; set; }
        public string extras { get; set; }
        public Nullable<int> extra_runs { get; set; }
        public string wicket_type { get; set; }
        public Nullable<int> dismissed_player_id { get; set; }
        public Nullable<int> fielder_id { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual Player Player2 { get; set; }
        public virtual Fixture Fixture { get; set; }
        public virtual Player Player3 { get; set; }
        public virtual Player Player4 { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery_Images> Delivery_Images { get; set; }
    }
}
