//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagementSystemBE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Images
    {
        public int id { get; set; }
        public string image_path { get; set; }
        public int deliveries_id { get; set; }
    
        public virtual delivery delivery { get; set; }
    }
}
