//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagementSystemBE.Models
{
    using System;  using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class FixturesImage
    {
        public int id { get; set; }
        public int fixtures_id { get; set; }
        public string imagePath { get; set; }
    
        [JsonIgnore] public virtual Fixture Fixture { get; set; }
    }
}
