//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagementSystemBE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsManagementSystemEntities : DbContext
    {
        public SportsManagementSystemEntities()
            : base("name=SportsManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<CricketScore> CricketScores { get; set; }
        public virtual DbSet<delivery> deliveries { get; set; }
        public virtual DbSet<Delivery_Images> Delivery_Images { get; set; }
        public virtual DbSet<Fixture> Fixtures { get; set; }
        public virtual DbSet<FixturesImage> FixturesImages { get; set; }
        public virtual DbSet<GoalBaseScore> GoalBaseScores { get; set; }
        public virtual DbSet<ManOfTheMatch> ManOfTheMatches { get; set; }
        public virtual DbSet<Match_events> Match_events { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PointsBaseScore> PointsBaseScores { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<ScoreCard> ScoreCards { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SessionSport> SessionSports { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TurnBaseGame> TurnBaseGames { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
