//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagementSystemBE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int id { get; set; }
        public int sports_id { get; set; }
        public string rules_of_game { get; set; }
    
        public virtual Sport Sport { get; set; }
    }
}
