//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagementSystemBE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionSport
    {
        public int id { get; set; }
        public Nullable<int> session_id { get; set; }
        public Nullable<int> sports_id { get; set; }
        public Nullable<int> managed_by { get; set; }
        public Nullable<int> no_of_teams { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual User User { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
