//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagementSystemBE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnBaseGame
    {
        public int id { get; set; }
        public Nullable<int> fixture_id { get; set; }
        public Nullable<int> winnner_id { get; set; }
        public Nullable<int> loser_id { get; set; }
    
        public virtual Fixture Fixture { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
